#!/bin/sh
set -e

if [ -d /var/www/html ]; then
	rm -rf /var/www/html
fi

DB_EXISTS=`psql -lqt | cut -d'|' -f1 | sed 's/\s//' | grep -w nominatim | wc -l`

if [[ -z "$DB_EXISTS" || "$DB_EXISTS" == "0" ]]; then
	cat <<-EOF > /var/nominatim/settings/local.php
	<?php
	$env = json_decode(file_get_contents('/etc/container_environment.json'));
	@define('CONST_Debug', (bool) $env->NOMINATIM_DEBUG);
	@define('CONST_Database_DSN', 'pgsql://'.$env->PGUSER.'@'.$env->PGHOST.'/nominatim');
	@define('CONST_Postgresql_Version', $env->PG_MAJOR);
	@define('CONST_Postgis_Version', $env->POSTGIS_VERSION);
	@define('CONST_Website_BaseURL', 'http://'.$env->NOMINATIM_WEBSITE_DOMAIN);
	EOF

	nominatim-setup
fi

exec nginx -g "daemon off;"