#!/bin/sh
set -e

if [ -d /var/www/html ]; then
	rm -rf /var/www/html
fi

DB_EXISTS=`psql -lqt` | cut -d -| -f 1 | grep -w nominatim | wc -l

if [ "${DB_EXISTS}" != "1" ]; then
	nominatim-setup
fi

exec nginx -g "daemon off;"